### ISSUE TITLE
Getting a watch error and stack trace when following the JavaScript tutorial

### ISSUE THREAD

**Issue by aquillano** [wercker/getting-started-nodejs#5]
I've followed the instructions in [Getting started with wercker & Javascript](http://devcenter.wercker.com/quickstarts/building/javascript.html).

I'm getting the following error and stack track after the watch step initializes [(Gist)](https://gist.github.com/aquillano/389262f40eff7cf9e401).

**Comment by rikgibson** [comment]
An old issue, but as I've just been updating the Javascript tutorial page I have tested this and it all seems fine now, so closing.
